/**
 * Typed event envelope shared by every Forge lifecycle event.
 *
 * Events are **notifications of committed state transitions**, never the authoritative
 * state store. PostgreSQL remains the sole durable source of truth; a lost subscriber or a
 * failed publication must never corrupt or erase PostgreSQL job state. See
 * `docs/architecture/events.md`.
 *
 * Field naming is deliberately `snake_case` to match the cross-boundary wire conventions
 * already used by {@link '@forge/contracts'.LogEntry} (`request_id`) and to keep the event
 * contract stable if it is later serialized onto an external transport.
 */

/**
 * Current event schema version. Bumped only on an incompatible change (see
 * `docs/architecture/events.md` § Versioning). Additive optional fields do NOT bump this.
 */
export const EVENT_SCHEMA_VERSION = 1 as const;

/**
 * The complete set of lifecycle event types Forge can describe.
 *
 * Some members are contract-only in this PR (no live producer yet) — they are listed so
 * the discriminated union and downstream exhaustiveness checks are complete from day one.
 * See the Event Catalog in `docs/architecture/events.md` for the authoritative producer and
 * publication status (`emitted` vs `deferred`) of each.
 */
export type ForgeEventType =
  | 'PipelineCreated'
  | 'PipelineQueued'
  | 'PipelineCompleted'
  | 'JobQueued'
  | 'JobClaimed'
  | 'JobStarted'
  | 'JobLogChunk'
  | 'JobSucceeded'
  | 'JobFailed'
  | 'JobCancelled'
  | 'WorkerRegistered'
  | 'WorkerHeartbeat'
  | 'WorkerLost';

/**
 * Ordered tuple of every event type — the runtime counterpart of {@link ForgeEventType},
 * used by schema construction and contract tests to guarantee full coverage.
 */
export const FORGE_EVENT_TYPES = [
  'PipelineCreated',
  'PipelineQueued',
  'PipelineCompleted',
  'JobQueued',
  'JobClaimed',
  'JobStarted',
  'JobLogChunk',
  'JobSucceeded',
  'JobFailed',
  'JobCancelled',
  'WorkerRegistered',
  'WorkerHeartbeat',
  'WorkerLost',
] as const satisfies readonly ForgeEventType[];

/**
 * Correlation identifiers carried on the envelope where the producing lifecycle can
 * populate them. All are plain strings that carry the same values as the branded domain
 * ids (`PipelineId`, `PipelineRunId`, `JobId`, `JobAttemptId`, `WorkerId`); the event layer
 * does not introduce a new id system.
 */
export interface EventCorrelation {
  readonly pipeline_id?: string;
  readonly run_id?: string;
  readonly job_id?: string;
  readonly attempt_id?: string;
  readonly worker_id?: string;
}

/**
 * Common envelope wrapping every typed event payload.
 *
 * @typeParam TType - the discriminant literal (`event_type`).
 * @typeParam TPayload - the type-specific payload shape.
 */
export interface ForgeEventEnvelope<
  TType extends ForgeEventType,
  TPayload,
> extends EventCorrelation {
  /**
   * Unique identifier for this individual event publication. Generated by Forge, immutable
   * once created, never derived from `event_type`. Suitable for downstream deduplication
   * under at-least-once delivery. See {@link './event-id.ts'.generateEventId}.
   */
  readonly event_id: string;
  /** Discriminant. */
  readonly event_type: TType;
  /** ISO 8601 UTC timestamp of when the event was constructed (wall clock, not causal). */
  readonly occurred_at: string;
  /** Schema version — always {@link EVENT_SCHEMA_VERSION} for events created by this build. */
  readonly version: typeof EVENT_SCHEMA_VERSION;
  /** Type-specific payload. Contains only information useful to consumers. */
  readonly payload: TPayload;
}
