import { randomUUID } from 'node:crypto';

/**
 * Regex for a canonical RFC 4122 v4 UUID (the shape {@link generateEventId} produces).
 * Exposed for contract tests and consumer-side validation.
 */
export const EVENT_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Generates a fresh, globally-unique event identifier.
 *
 * Properties (see `docs/architecture/events.md` § Event Identity):
 * - generated by Forge, never supplied by a caller in production paths;
 * - immutable once assigned to an event;
 * - never derived from `event_type` — two events of the same type get different ids;
 * - suitable for downstream deduplication under at-least-once delivery.
 *
 * This is NOT a claim of exactly-once publication: a producer that retries after a crash
 * will legitimately mint a new id for the re-publication. Consumers dedupe on `event_id`
 * for the events they actually received, and additionally rely on idempotent handlers.
 */
export function generateEventId(): string {
  return randomUUID();
}

/** True when `value` is a well-formed event id. */
export function isEventId(value: unknown): value is string {
  return typeof value === 'string' && EVENT_ID_PATTERN.test(value);
}
